name: Codespell

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened, ready_for_review]
  repository_dispatch:
    types: [nightly-trigger]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    name: Check spelling
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wolfssl/wolftpm-ci:v1.1
    defaults:
      run:
        shell: bash
    timeout-minutes: 5
    steps:
      - name: Checkout wolfTPM
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run codespell
        run: |
          codespell --count \
            --skip '.git,./lib,./IDE,./certs,./m4,*.der,*.pem,*prebuilt_bindings.rs' \
            --ignore-words-list 'inh,inout,keypair,nd,parm,rcv,ser,loadIn,importIn,certifyIn,bu,fo,daa,pris,hsi,fram,hart,cna'
