name: Zephyr wolfTPM Tests

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened, ready_for_review]
  repository_dispatch:
    types: [nightly-trigger]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_test:
    name: Build
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    strategy:
      matrix:
        config:
          - zephyr-ref: v3.4.0
            zephyr-sdk: 0.16.1
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/wolfssl/wolftpm-ci:v1.1
    defaults:
      run:
        shell: bash
    # This should be a safe limit for the tests to run.
    timeout-minutes: 25
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk-${{ matrix.config.zephyr-sdk }}
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    steps:
      - name: Checkout wolfTPM
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use the image's Zephyr environment
        run: echo "/opt/zephyr-python/bin" >> "$GITHUB_PATH"

      - name: Init west workspace
        run: west init --mr ${{ matrix.config.zephyr-ref }} zephyr

      - name: Update west.yml
        working-directory: zephyr/zephyr
        run: |
          REF=$(echo '${{ github.ref }}' | sed -e 's/\//\\\//g')
          sed -e 's/remotes:/remotes:\n    \- name: wolfssl\n      url\-base: https:\/\/github.com\/wolfssl/' -i west.yml
          sed -e "s/remotes:/remotes:\n    \- name: wolftpm\n      url\-base: https:\/\/github.com\/${{ github.repository_owner }}/" -i west.yml
          sed -e "s/projects:/projects:\n    \- name: wolftpm\n      path: modules\/lib\/wolftpm\n      remote: wolftpm\n      revision: $REF/" -i west.yml
          sed -e 's/projects:/projects:\n    \- name: wolfssl\n      path: modules\/crypto\/wolfssl\n      remote: wolfssl\n      revision: master/' -i west.yml

      - name: Update west workspace
        working-directory: zephyr
        run: west update -n -o=--depth=1

      - name: Export zephyr
        working-directory: zephyr
        run: west zephyr-export

      - name: Build wolftpm tests
        id: wolftpm_build
        working-directory: zephyr
        run : |
          west build -p auto -b qemu_x86 modules/lib/wolftpm/zephyr/samples/wolftpm_wrap_test
          west build -p auto -b qemu_x86 modules/lib/wolftpm/zephyr/samples/wolftpm_wrap_caps

      # skipping tests, because no simulator TPM to run
      #- name: Run wolftpm tests
      #  id: wolftpm_tests
      #  working-directory: zephyr
      #  run: |
      #    ./zephyr/scripts/twister --testsuite-root modules/lib/wolftpm --test zephyr/samples/wolftpm_wrap_caps/sample.lib.wolftpm_wrap_caps -vvv
      #    rm -rf zephyr/twister-out
      #    ./zephyr/scripts/twister --testsuite-root modules/lib/wolftpm --test zephyr/samples/wolftpm_wrap_test/sample.lib.wolftpm_wrap_test -vvv
      #    rm -rf zephyr/twister-out

      - name: Zip failure logs
        if: ${{ failure() && steps.wolftpm_build.outcome == 'failure' }}
        run: |
          zip -9 -r logs.zip zephyr/twister-out

      - name: Upload failure logs
        if: ${{ failure() && steps.wolftpm_build.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-client-test-logs
          path: logs.zip
          retention-days: 5
